#pragma once

#include "../vendor/cppapiframework/src/Database/CSql.hpp"
#include "../vendor/cppapiframework/src/WebInterface/CController.hpp"
#include "../vendor/cppapiframework/src/WebInterface/CPistacheEndpoint.hpp"
#include "../vendor/cppapiframework/src/jobhandler/JobsHandler.hpp"
#include "../vendor/cppapiframework/src/jobhandler/QueueWorker.hpp"
#include "../vendor/cppapiframework/src/queues/RedisQueue.hpp"
#include "../vendor/cppapiframework/src/utils/CConfig.hpp"
#include "../vendor/cppapiframework/src/utils/CLog.hpp"
#include "../vendor/cppapiframework/src/utils/LogUtils.hpp"
#include "../vendor/cppapiframework/src/utils/RedisService.hpp"
#include <Poco/Crypto/DigestEngine.h>
#include <Poco/Dynamic/Var.h>
#include <Poco/HMACEngine.h>
#include <Poco/JSON/JSON.h>
#include <Poco/JSON/Parser.h>
#include <Poco/UUID.h>
#include <Poco/UUIDGenerator.h>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <memory>
#include <mutex>
#include <optional>
#include <random>
#include <string>
#include <string_view>
#include <utility>
#include <vector>
